## NumPy : Numeric Python
NumPy is the package of scientific computing

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

a powerful N-dimensional array (Ndarray) object
sophisticated (broadcasting) functions
tools for integrating C/C++ and Fortran code
useful linear algebra, Fourier transform, and random number capabilities

#### The more important attributes of an ndarray object are:

ndarray.ndim : the number of axes (dimensions) of the array.

ndarray.shape : the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

ndarray.size : the total number of elements of the array. This is equal to the product of the elements of shape.

ndarray.dtype : an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

ndarray.itemsize : the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

ndarray.data : the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [10]:
import numpy as np
a = np.arange(15)# Create one-dimenstional array using arange() function
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [11]:
#check the dimenstion of array
print(a.ndim) 

1


In [12]:
#Reshape array 
a= a.reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [13]:
#check the shape of array (rows, columns)
print(a.shape)

(3, 5)
2


In [14]:
#check the size of array (the total number of elements of the array)
print(a.size)

15


In [15]:
#check data type of array
print(a.dtype)

int32


In [16]:
#check itemsize of array
print(a.itemsize)

4


In [17]:
#check type of array
print(type(a))

<class 'numpy.ndarray'>


#### Creating a NumPy Array - Single Dimensional Array

There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [20]:
import numpy as np

a = np.array([2,3,4])
print("array:", a)
print(a.dtype)


array: [2 3 4]
int32


In [21]:
# Note: A frequent error consists in calling array with multiple numeric arguments, 
#      rather than providing a single list of numbers as an argument.

a = np.array(1,2,3,4) #Wrong
print(a)

a = np.array([1,2,3,4])  # RIGHT

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

#### Creating an array of numbers of a specific range or using range function

In [23]:
import numpy as np

a = np.arange(10, 100, 2) # np.arange(start, stop, step)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


#### Creating a linearly spaced vector, with spacing



In [24]:
import numpy as np

vector = np.linspace(0, 20, 5)
print(vector)

[ 0.  5. 10. 15. 20.]


#### Creating an array using existing data

In [25]:
import numpy

x = [1,2,3]
a = numpy.asarray(x)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


#### Reshape or Restructuring a NumPy Array:

One-dimensional arrays are then printed as rows, bidimensionals (two dimensional) as matrices and tridimensionals (three dimensional)as lists of matrices.

In [31]:
import numpy as np

# one dimensional or 1D array
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [29]:
#bidimensional or two dimensional array or 2D array
b = np.arange(12)
print(b.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
#three dimensional or 3D array
c = np.arange(24)
print(c.reshape(2,3,4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


#### NumPy Attributes:

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [32]:
a = np.zeros( (3,4) )
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
b = np.ones( (2,3,4), dtype=np.int16 )
print(b)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [34]:
c = np.empty((2,3))
print(c)

[[2.12199579e-314 6.36598737e-314 1.06099790e-313]
 [1.48539705e-313 1.90979621e-313 2.33419537e-313]]


#### Flatten the 3D array to get back the linear array: : ravel() function

In [35]:
b = np.ones((2,3,4))
print(b)

print(b.ravel())

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Basic Operation

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [ ]:
import numpy as np

a = np.array([10,20,30,40])

b = np.arange(4)

c = a + b # addition
print(c)

d = a - b # subtraction
print(d)

e = a * b # multiplication
print(e)

print(b**2) # expontial

print(a<25) # Boolen values

print(np.sqrt(a)) #Square root value of each element of array

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [ ]:
a = np.random.random((2,3))
print(a)

print("sum:", a.sum())

print("min", a.min())

print("max:", a.max())

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [ ]:
b = np.arange(12).reshape(3,4)

print(b)

# sum of each column
print(b.sum(axis = 0))

# min of each row
print(b.min(axis = 1))

#cumulative sum along each row
print(b.cumsum(axis = 1))

NumPy provides the option of importing data from files directly into ndarray using the loadtxt () function

The savetxt() function can be used to write data from an array into the text file

In [ ]:
arr = np.loadtxt('filex.txt')
np.savetxt('newfilex.txt')