<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [1]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists

r=int(input("enter the number of rows for First matrix:"))
c=int(input("enter the number of columns for First matrix:"))
print("Enter the elements of First Matrix:")
A=[[0 for i in range(c)] for j in range(r)]    #initialise matrix A to zero
for i in range(r):                             # user input for matrix A
    for j in range(c):
        row=int(input())                      
        A[i][j]=row 
        
r1=int(input("enter the number of rows for Second matrix:"))                  
c1=int(input("enter the number of columns for Second matrix:"))
print("Enter the elements of Second Matrix:")
B=[[0 for i in range(c1)] for j in range(r1)]             #initialise matrix B to zero 
for i in range(r1):                                       # user input for matrix B
    for j in range(c1):
        row=int(input())
        B[i][j]=row             

if (c==r1):                               #If the number of columns of first matrix is equal to number of rows of second matrix
    final_result=[[0,0,0],[0,0,0],[0,0,0]] 
    for i in range(len(A)):                             #Loop through rows of first matrix
        for j in range(len(B[0])):                      #Loop through columns of second matrix
            for k in range(len(B)):                     #Loop through rows of second matrix
                final_result[i][j] += A[i][k]*B[k][j]  
    print("Matrix multiplication of A and B is:")
    for a in final_result:
        print(a)
else:
    print('Multiplication is not possible')

enter the number of rows for First matrix:3
enter the number of columns for First matrix:3
Enter the elements of First Matrix:
1
2
3
4
5
6
7
8
9
enter the number of rows for Second matrix:3
enter the number of columns for Second matrix:3
Enter the elements of Second Matrix:
2
5
6
9
7
4
1
5
6
Matrix multiplication of A and B is:
[23, 34, 32]
[59, 85, 80]
[95, 136, 128]


## <h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [66]:
from random import uniform
from bisect import bisect
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

A = [0,5,27,6,13,28,100,45,10,79]

def pick_a_number_from_list(A):
    count=0
    cum_sum =[]
    # Loop through the whole list A and calculate the sum of all elements and store it in a list
    for i in range(len(A)):
        count += A[i]
        cum_sum.append(count)
    
    n =100      # Number of times the element is selected
    rand=[]
    for j in range(n):
        a=random.uniform(0.0,count)  # to pick a random number from 0 to sum of all elements
        b=bisect(cum_sum,a)
        rand.append(A[b])
    
    return rand    

pick_a_number_from_list(A)

Reference : https://www.w3schools.com/python/ref_random_uniform.asp
            https://stackoverflow.com/questions/212358/binary-search-bisection-in-python

[100,
 45,
 45,
 100,
 45,
 6,
 100,
 79,
 100,
 27,
 13,
 79,
 100,
 45,
 45,
 100,
 100,
 100,
 100,
 45,
 45,
 79,
 27,
 100,
 27,
 79,
 79,
 45,
 28,
 79,
 79,
 100,
 45,
 28,
 79,
 100,
 100,
 79,
 100,
 28,
 45,
 100,
 45,
 100,
 79,
 100,
 79,
 27,
 79,
 79,
 100,
 79,
 5,
 100,
 45,
 100,
 100,
 79,
 79,
 27,
 45,
 100,
 79,
 100,
 5,
 45,
 6,
 27,
 45,
 6,
 79,
 45,
 100,
 100,
 27,
 79,
 28,
 45,
 27,
 28,
 100,
 28,
 100,
 5,
 79,
 100,
 79,
 100,
 100,
 45,
 79,
 28,
 79,
 10,
 45,
 100,
 27,
 27,
 100,
 100]

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [3]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):

    #re.sub is used for replacing the strings
    String= re.sub("\D","",String)   # "\D" - Returns a match where the string DOES NOT contain digits
    String= re.sub("\d","#",String)  # "\d" -Returns a match where the string contains digits (numbers from 0-9)
    return(String) 

print(replace_digits('1s235df3'))
print(replace_digits('23wa4'))

Reference : https://www.w3schools.com/python/python_regex.asp

#####
###


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [70]:
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] 
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(Students, Marks):
    #Converting both the lists into a dictionary using zip
    a_dict={key:value for key,value in zip(Students,Marks)}
    
    print("Top 5 Students:")
    #Using the sorted function in dictionary to print the top 5 students
    for key,value in sorted(a_dict.items(),key=lambda item:item[1],reverse=True)[:5]:
        print(key,'->',value)
    
    print("\nBottom 5 Students:")
    #Using the sorted function in dictionary to print the bottom 5 students
    for key,value in sorted(a_dict.items(),key=lambda item:item[1])[:5]:
        print(key,'->',value)
    
    print("\nStudents between 25th and 75th percentile:")
    for key,value in sorted(a_dict.items(),key=lambda item:item[1]):
        max_marks=max(Marks)
        min_marks=min(Marks)
        diff=max_marks - min_marks
        per_25=0.25*diff
        per_75=0.75*diff
        if per_25<value<per_75:
            print(key,'->',value)

display_dash_board(Students, Marks)


Reference: https://realpython.com/iterate-through-dictionary-python/

Top 5 Students:
student8 -> 98
student10 -> 80
student2 -> 78
student5 -> 48
student1 -> 45

Bottom 5 Students:
student3 -> 12
student4 -> 14
student9 -> 35
student6 -> 43
student1 -> 45

Students between 25th and 75th percentile:
student9 -> 35
student6 -> 43
student1 -> 45
student7 -> 45
student5 -> 48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [35]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
d=[]

def closest_points_to_P(S,P):
    #looping through the list of tuples S and applying cosine distance formula to each of the points
    for i in range(len(S)):
        cosdist= math.acos(((S[i][0]*P[0])+(S[i][1]*P[1]))/((math.sqrt((S[i][0]**2)+(S[i][1]**2)))*(math.sqrt((P[0]**2)*(P[1]**2)))))
        d.append(cosdist) #Adding the points to the list d

closest_points_to_P(S,P)

# Converting the lists S,d into a dictionary and sorting them to find out the 5 nearest points in list S from P
a_dict={key:value for key,value in zip(S,d)}
for key,value in sorted(a_dict.items(),key=lambda items:items[1])[:5]:
    print(key,'->',value)
           
                
Reference : https://learnandlearn.com/python-programming/python-reference/find-inverse-cosine-python           


(6, -7) -> 1.141992331211475
(1, -1) -> 1.1456227006265225
(6, 0) -> 1.318116071652818
(-5, -8) -> 1.4200597817262512
(-1, -1) -> 1.5118366078609264


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [28]:
import math
import re

# Using the string replace function to replace x,y with the given points from Red,Blue.
# To get the red points on one side,the sign of the point should be positive and above the line or the sign should be negative 
# and below the line. Same applies for Blue points 
def equation(red,blue,line):
    sign=1
    if eval(line.replace('x','*%s'% red[0][0]).replace('y','*%s'% red[0][1])) > 0:  # 
        sign=1
 #If the sign is positive and the point lies below the line or if the sign is negative and lies above the line then return NO
    for pts in red:
        if sign== 1 and eval(line.replace('x','*%s' % pts[0]).replace('y','*%s' % pts[1])) < 0:
            return 'NO'
        
        if sign== -1 and eval(line.replace('x','*%s' % pts[0]).replace('y','*%s' % pts[1])) >0:
            return 'NO'
        
    sign_of_b = -1
#If the sign is positive and the point lies below the line or if the sign is negative and lies above the line then return NO
    for pts in blue:
        if sign_of_b == 1 and eval(line.replace('x','*%s'% pts[0]).replace('y','*%s' % pts[1])) < 0:
            return 'NO'
        if sign_of_b == -1 and eval(line.replace('x','*%s'% pts[0]).replace('y','*%s' % pts[1])) > 0:
            return  'NO'
    return "YES"


Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    a= equation(Red,Blue,i)
    print(a)
    
Reference : https://www.w3schools.com/python/ref_string_replace.asp    

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [34]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(S):
    a= S.split(',')
    count=0
    value=0
# Divide the blank spaces to the left number equally by n+1 spaces    
    for i in range(len(a)):
        if a[i] == '_':
            count=count+1
        else:
            for j in range(i+1):
                a[j]=str((float(a[i]))/(count+1))
                value=i
                mid_value=float(a[i])
            break
#For blanks in the middle ,finding out how many blanks are placed between the first number and second number and dividing them equally   
    sec_num=1
    j=0
    for ele in range(value+1,len(a)):
        if a[ele]!= '_':
            sec_num=(ele + 1 - value)
            j = ele
            break
    
    k = float(a[j])
    for q in range(value,j+1):
          a[q]=str((mid_value+k)/sec_num)
 
 # blanks at the end           
    last_num=float(a[j])
    for s in range(j,len(a)):
        a[s]=str(((last_num)/(len(a)-j)))
        
    return a
def smoothing(S):
    a= S.split(',')
    count=0
    value=0   
    for i in range(len(a)):
        if a[i] == '_':
            count=count+1
        else:
            for j in range(i+1):
                a[j]=str((float(a[i]))/(count+1))
                value=i
            break
    num=float(a[i])
    for s in range(i,len(a)):
        a[s]=str(((num)/(len(a)-i)))
    return a 



S= "_,_,_,24"
S1= "40,_,_,_,60"
S2="80,_,_,_,_"
S3= "_,_,30,_,_,_,50,_,_"

print(smoothing(S))
print(curve_smoothing(S1))
print(smoothing(S2)) 
print(curve_smoothing(S3))



['6.0', '6.0', '6.0', '6.0']
['20.0', '20.0', '20.0', '20.0', '20.0']
['16.0', '16.0', '16.0', '16.0', '16.0']
['10.0', '10.0', '12.0', '12.0', '12.0', '12.0', '4.0', '4.0', '4.0']


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [4]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

dictionary={'F1S1':0,'F1S2':0,'F1S3':0,'F2S1':0,'F2S2':0,'F2S3':0,'F3S1':0,'F3S2':0,'F3S3':0,'F4S1':0,'F4S2':0,'F4S3':0,'F5S1':0,'F5S2':0,'F5S3':0}
dictionary1={'S1':0,'S2':0,'S3':0}

# we have to deploy the formula of conditional probability for each of the cases:
#P(A|B)=(P(A & B)/P(B))
def compute_conditional_probabilites(A):
    # your code
    for i in range(len(A)):                             #Looping through each case to find P(A & B) and P(B)
        if(A[i][0]=='F1' and A[i][1]=='S1'):
            dictionary['F1S1']+=1
            dictionary1['S1']+=1
        if(A[i][0]=='F1' and A[i][1]=='S2'):
            dictionary['F1S2']+=1
            dictionary1['S2']+=1    
        if(A[i][0]=='F1' and A[i][1]=='S3'):
            dictionary['F1S3']+=1
            dictionary1['S3']+=1    
        if(A[i][0]=='F2' and A[i][1]=='S1'):
            dictionary['F2S1']+=1
            dictionary1['S1']+=1
        if(A[i][0]=='F2' and A[i][1]=='S2'):
            dictionary['F2S2']+=1
            dictionary1['S2']+=1
        if(A[i][0]=='F2' and A[i][1]=='S3'):
            dictionary['F2S3']+=1
            dictionary1['S3']+=1    
        if(A[i][0]=='F3' and A[i][1]=='S1'):
            dictionary['F3S1']+=1
            dictionary1['S1']+=1 
        if(A[i][0]=='F3' and A[i][1]=='S2'):
            dictionary['F3S2']+=1
            dictionary1['S2']+=1 
        if(A[i][0]=='F3' and A[i][1]=='S3'):
            dictionary['F3S3']+=1
            dictionary1['S3']+=1   
        if(A[i][0]=='F4' and A[i][1]=='S1'):
            dictionary['F4S1']+=1
            dictionary1['S1']+=1
        if(A[i][0]=='F4' and A[i][1]=='S2'):
            dictionary['F4S2']+=1
            dictionary1['S2']+=1 
        if(A[i][0]=='F4' and A[i][1]=='S3'):
            dictionary['F4S3']+=1
            dictionary1['S3']+=1
        if(A[i][0]=='F5' and A[i][1]=='S1'):
            dictionary['F5S1']+=1
            dictionary1['S1']+=1
        if(A[i][0]=='F5' and A[i][1]=='S2'):
            dictionary['F5S2']+=1
            dictionary1['S2']+=1     
        if(A[i][0]=='F5' and A[i][1]=='S3'):
            dictionary['F5S3']+=1
            dictionary1['S3']+=1    

compute_conditional_probabilites(A)             #Dividing P(A|B) by P(B) to find out the probability of each case

print('P(F1S1)=',(dictionary['F1S1']/dictionary1['S1']))
print('P(F1S2)=',(dictionary['F1S2']/dictionary1['S2']))
print('P(F1S3)=',(dictionary['F1S3']/dictionary1['S3']))
print('P(F2S1)=',(dictionary['F2S1']/dictionary1['S1']))
print('P(F2S2)=',(dictionary['F2S2']/dictionary1['S2']))
print('P(F2S3)=',(dictionary['F2S3']/dictionary1['S3']))
print('P(F3S1)=',(dictionary['F3S1']/dictionary1['S1']))
print('P(F3S2)=',(dictionary['F3S2']/dictionary1['S2']))
print('P(F3S3)=',(dictionary['F3S3']/dictionary1['S3']))
print('P(F4S1)=',(dictionary['F4S1']/dictionary1['S1']))
print('P(F4S2)=',(dictionary['F4S2']/dictionary1['S2']))
print('P(F4S3)=',(dictionary['F4S3']/dictionary1['S3']))
print('P(F5S1)=',(dictionary['F5S1']/dictionary1['S1']))
print('P(F5S2)=',(dictionary['F5S2']/dictionary1['S2']))
print('P(F5S3)=',(dictionary['F5S3']/dictionary1['S3']))



Reference:https://en.wikipedia.org/wiki/Conditional_probability

P(F1S1)= 0.25
P(F1S2)= 0.3333333333333333
P(F1S3)= 0.0
P(F2S1)= 0.25
P(F2S2)= 0.3333333333333333
P(F2S3)= 0.3333333333333333
P(F3S1)= 0.0
P(F3S2)= 0.3333333333333333
P(F3S3)= 0.3333333333333333
P(F4S1)= 0.25
P(F4S2)= 0.0
P(F4S3)= 0.3333333333333333
P(F5S1)= 0.25
P(F5S2)= 0.0
P(F5S3)= 0.0


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [13]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    a=[]
    Str1=set(S1.split())
    Str2=set(S2.split())
    a=Str1 & Str2                          # Same words contained in both set Str1 and Str2
    print(len(a))
    
    b=[]
    b=list(Str1-Str2)                      # Words contained in only S1 and not in S2
    print(b)
    
    c=[]
    c=list(Str2-Str1)                      # words contained in only S2 and not in S1
    print(c)


S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"

string_features(S1, S2)



Reference : https://www.w3schools.com/python/ref_string_split.asp

7
['F', 'first', '5']
['S', 'second', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [2]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    count=0
    for i in range(len(A)):
        #Applying the given formula to the above list A and adding it to a variable called count
        
        count=count + ((A[i][0]* math.log(A[i][1],10)) + ((1-A[i][0]) * (math.log(1-A[i][1],10))))
      
    return count


(compute_log_loss(A)/8)*(-1)

Reference:https://www.w3schools.com/python/ref_math_log.asp

0.42430993457031635